### ISSUE TITLE
Analyze is unable to process all files for some unknown reason

### ISSUE THREAD

**Issue by ladytaz-rowell** [ferstl/depgraph-maven-plugin#160] opened 2022-07-26 14:03 UTC
As a result, the analyze process does not recognize all the libraries needed, and incorrectly tells you they are not used. 

![Screen Shot 2022-07-26 at 10 01 40 AM](https://user-images.githubusercontent.com/54676734/181025033-5ac5b369-37e9-400a-a32a-ed6133f5a393.png)

**Comment by ferstl** [comment] 2022-07-27 20:24
Hi @ladytaz-rowell 
Based on your screenshot the problem seems to be in the *maven-dependency-plugin* not in the depgraph-maven-plugin. Take a look at https://github.com/apache/maven-dependency-plugin to find out how to file bugs for the maven-dependency-plugin.
I'm closing this issue for now. If you still think the problem is related to the depgraph-maven-plugin, feel free to reopen this issue and provide some more information about how to reproduce this problem.

Cheers,
Stefan

**Closed by ferstl** 2022-07-27 20:24 UTC
Labels: invalid

**Comment by ladytaz-rowell** [comment] 2022-08-05 12:45
I know this is closed but wanted to let you know that the issue was with class files using lambdas. I am compiling with Java 8 and I believe the maven-dependency-plugin is defaulting to an old version based on the version of the Java. Not sure why it is not choosing a higher version since Java 8 supports lambdas. With that being said, I was able to override the plugin version by adding the plugin to my pom with the latest version and maven started using the newer plugin. This fixed the problem.
