### ISSUE TITLE
Include parent into graph

### ISSUE THREAD

**Issue by Witko** [ferstl/depgraph-maven-plugin#70] opened 2017-11-16 12:35 UTC
I'm trying to cover whole internal module structure to a graph. This includes both dependencies and hierarchy. It would be very nice if this plugin would be able to do that.

**Comment by ferstl** [comment] 2017-11-17 15:13
If you are using the `aggregate` goal you can enable the [`includeParentProjects`](https://ferstl.github.io/depgraph-maven-plugin/aggregate-mojo.html#includeParentProjects) option. It should do exactly what you need, if I understand you correctly.

**Comment by ferstl** [comment] 2017-11-21 21:29
Hi @Witko 
> it includes the parents but not shown with dotted line...

That is correct. Showing dotted lines between parents and their modules is not possible anymore since the introduction of the custom styling options in Version 2.0.x. I'll adjust the documentation accordingly.

> ...and other dependencies are not there. So it shows just parent hierarchy now. I'd like to see both. I it possible?

Yes, you should see both unless you didn't exclude other dependencies.
I created a branch with a little example project and cannot reproduce the problem. The resulting graph contains the parent, its modules as well as all dependencies.
You can find the example project here: https://github.com/ferstl/depgraph-maven-plugin/tree/bugfix/%2370-investigation/src/test/projects/issue-70
The test, which calls `mvn clean package depgraph:aggregate -DcreateImage -DincludeParentProjects`, is here: https://github.com/ferstl/depgraph-maven-plugin/blob/bugfix/%2370-investigation/src/test/java/com/github/ferstl/depgraph/Issue70IntegrationTest.java#L59

The resulting (dot) graph looks like this:
![image](https://user-images.githubusercontent.com/1487727/33097181-958a6b6c-cf09-11e7-8102-e73ca753e96f.png)

`parent` and `sub-parent` are POMs that have `module-1` - `module-3` as `<modules>`. The other nodes are external dependencies.

> Also my parent is in artifactory - can this plugin handle it?

Yes, it can. Maven and this plugin do internally use a library called [Maven Resolver](https://maven.apache.org/resolver/) (formerly known as Eclipse Aether) which handles the dependency resolution. The resolver is agnostic to the underlying repository managers like Artifactory, Nexus, etc.

**Comment by Witko** [comment] 2017-11-22 14:36
Hi @ferstl ,
Firstly thank you very much for your effort in helping me.

I've attached([issue-70.zip](https://github.com/ferstl/depgraph-maven-plugin/files/1496272/issue-70.zip)) an example to demonstrate the bahaviour(Running __aggregate__ on root)

 
This is the graph it produces:
![dependency-graph](https://user-images.githubusercontent.com/658494/33132211-43fba85c-cf99-11e7-9aee-d6d75b9dd8f7.png)
Im missing there the dependencies for the module-0(this is produced by running __graph__ in module-0):
![dependency-graph](https://user-images.githubusercontent.com/658494/33132278-8f58a07a-cf99-11e7-8163-6f62d6f5ad11.png)


Also noticed in the dot that for the graph the artifact nodes were named without scope(missing compile) and on aggregate it was present.

This is the expected result(adjusted by hand):
![result](https://user-images.githubusercontent.com/658494/33132614-67254daa-cf9a-11e7-9fea-05e3240b94cf.png)

**Comment by ferstl** [comment] 2017-11-23 10:58
There was indeed a problem when `<module>`s have different parents than the POM defining the modules, like the parent project ans spring-boot-starter in your example. The problem is **fixed in version 3.0.1** which should be on Maven Central within the next few hours.

Regarding the different handling of scopes in the `graph`  and `aggregate` goals: When creating a graph of a single module, each dependency has exactly one scope. That's why it is not part of the node identifier in the dot file. An aggregated graph is kind of the union of all modules' dependency graphs. There, the same dependency can appear in different scopes. If you don't want to have multiple nodes for the same dependency in different scopes, you can set the property `mergeScopes=true` on aggregated graphs.

**Closed by ferstl** 2017-11-23 10:58 UTC
Labels: bug, on-master

**Comment by Witko** [comment] 2017-11-24 12:01
Great thank you!
